Script started on Sat 27 Aug 2022 06:36:50 PM EDT
cis-lclient15:~/lab1>cc lab1.c
cis-lclient15:~/lab1>./a.out
Please enter fahrenheit number you want to convert:44  90
The value of fahrenheit is 90.000000 
The value in celcius is 32.222222cis-lclient15:~/lab1>cc lab1.c
cis-lclient15:~/lab1>./a.out
Please enter fahrenheit number you want to convert:44
The value of fahrenheit is 44.000000 
The value in celcius is 6.666667cis-lclient15:~/lab1>cc lab1.c
cis-lclient15:~/lab1>./a.out
Please enter fahrenheit number you want to convert:-5
The value of fahrenheit is -5.000000 
The value in celcius is -20.555556cis-lclient15:~/lab1>cc lab1.c
cis-lclient15:~/lab1>.a[K/a.out
Please enter fahrenheit number you want to convert:212
The value of fahrenheit is 212.000000 
The value in celcius is 100.000000cis-lclient15:~/lab1>cc lab1.c
cis-lclient15:~/lab1>./a.out
Please enter fahrenheit number you want to convert:32
The value of fahrenheit is 32.000000 
The value in celcius is 0.000000cis-lclient15:~/lab1>cc lab1.c
cis-lclient15:~/lab1>.a[K/a.out
Please enter fahrenheit number you want to convert:500
The value of fahrenheit is 500.000000 
The value in celcius is 260.000000cis-lclient15:~/lab1>cc lab.[K1.c
cis-lclient15:~/lab1>-40[K[K[K./a.out
Please enter fahrenheit number you want to convert:-40
The value of fahrenheit is -40.000000 
The value in celcius is -40.000000cis-lclient15:~/lab1>exit
exit

Script done on Sat 27 Aug 2022 06:38:56 PM EDT
