#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <unistd.h>
#include "../include/myheader.h"

//prototypes
void fill_random(int arr[], int array_size);
void print_array(int arr[], int array_size);

int main(){

//Declares an intializes a constant for the size of the array
const int size_test_array = 10;

//Declares the int array to be sorted
int test_array[size_test_array];

//Calls fill_random and print_array
fill_random(test_array, size_test_array);
print_array(test_array, size_test_array);

return EXIT_SUCCESS;

}

void fill_random(int arr[], int array_size)
/*
 * Preconditions:
 *      array arr[]-         An integer array
 *      variable array_size- An int that represents the size of arr[]
 * Postconditions:           An integer array (arr[]) with array_size number of elements
 *                           with values between 0 and 200.
 * Globals:                  NULL-
 * Returns:                  NONE
 * Description:              Takes an integer array and a given size and fills the array with a number of elements equal to the size,
 *                           where the elements have values between 0 and 200.
 *
 */
{
srandom(time(NULL) + getpid());

//Declares var to store values generated by random()
int rand;

//Loop Control Variable and Array Subscript
int i;

//Fills the array with a certain number elements depending on the value of array_size
for(i = 0; i<array_size; i++){
	rand = random() % (201);	
	arr[i] = rand;
}

}

void print_array(int arr[], int array_size)
/*
 * Preconditions:
 *      array arr[]-         An integer array
 *      variable array_size- An int that represents the size of arr[]
 * Postconditions:           Exits function after printing {} is array is empty
 * Globals:                  NONE
 * Returns:                  NONE
 * Description:              Prints out every item in an integer array.
 *
 */
{

    //Declares loop control variable
    int i;

    //Prints out {} if array has no elements
    if (array_size == 0)
    {
        printf("{}");
        return;
    }

    //Prints out first element of array
    printf("{%d", arr[0]);
    
    //Prints out other array elements
    for (i = 1; i < size; i++)
    {
        printf(", %d", arr[i]);
    }

    printf("}\n");
}
